public class PrimitiveDtaTypeDemo {
    public void printBasicDataType() {

    }
    public void printBasicDataType3(string bn,  integer candidates, boolean ac ){
string batchname = bn;
integer totalCandidates= candidates;
boolean isAdminCompleted = ac;

string batchDescription = batchName + ' are the bestest ';
system.debug(batchDescription);
system.debug('total of candidates: ' + totalCandidates );
system.debug('is Admin completed ' + isAdminCompleted);



    }
}