/*SalesforceDevoleper adında bir Class oluşturun ve bu class, myFirstCode adında bir 
methoda sahip olsun. System.debug yardımı ile methodun içinde favori şehir, film ve 
mevsiminizi ayrı satırlarda olacak şekilde yazdırın.*/

public  class SalesforceDeveloper {
    public void myFirstCode() {
string favoriteCity = 'samsun';
system.debug('My favorite  city is '+ favoriteCity);
string favoriteMovie = 'Titanic';
system.debug('My favorite  Movie is '+ favoriteMovie);
string favotiteSeason = 'Winter';
system.debug('My favorite season is '+ favotiteSeason);
    }


/*SalesforceDevoleper Class’ında bulunan myFavorites method unun içinde, biri string 
diğeri integer iki variable oluşturun. Bu variablelar favori numaranızı ve bulunduğunuz 
şehri içersin. System.debug yardımı ile bu variableları örnekteki gibi yazdırın.*/

public void myFavorites(){

string favoriteCity = 'sansun';
system.debug(favoriteCity);
integer favoriteNumber = 5;
system.debug(favoriteNumber);
system.debug('favori numaram: ' + favoriteNumber + 'favori sehrim: ' + favoriteCity);



}
}