public class MathematicalClass {
    public integer add (integer num1, integer num2) {
integer sum1= num1+num2;
return sum1;
    }
    public integer subtraction( integer num1, integer num2){
        integer sum2 = num1-num2;
        return sum2;
    }
    public integer division ( integer num1, integer num2){
        integer sum3 = num1/num2;
        return sum3;
    }
    public integer multiplication ( integer num1, integer num2){
        integer sum4 = num1*num2;
        return sum4;
    }


}
